CREATE TABLE IF NOT EXISTS CUSTOMERS (
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    GRADE INTEGER
);

INSERT INTO CUSTOMERS (NAME, ADDRESS, GRADE) VALUES
    ('RAMESH', 'DELHI', 120),
    ('SAM', 'NEW YORK', 99),
    ('RAMESH', 'MELBOURNE', 87),
    ('BOLT', 'NEW YORK', 120);

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE ADDRESS = 'NEW YORK' OR GRADE > 100;

SELECT * FROM CUSTOMERS WHERE ADDRESS = 'NEW YORK' AND GRADE > 100;
